server:
  port: 8080

spring:
  application:
    name: Backend-Onboarding-Java

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
      format_sql: true

logging.level:
  org.hibernate.SQL: debug